openapi: 3.0.0
info:
  title: Dashlane public API documentation Teams Time API
  description: This is Dashlane public API documentation
  contact:
    name: Dashlane API team
    email: contact@dashlane.com
    url: https://www.dashlane.com
  version: '2026-07-17T15:19:22.696Z'
servers:
- url: https://api.dashlane.com/public
  description: The production API server
tags:
- name: Time
paths:
  /time/GetRemoteTime:
    get:
      tags:
      - Time
      description: Retrieve the UNIX timestamp (in seconds) of the current time according to Dashlane servers
      operationId: GET-time-GetRemoteTime
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  data:
                    type: object
                    properties:
                      timestamp:
                        description: The UNIX timestamp of the current time
                        type: integer
                    additionalProperties: false
                    required:
                    - timestamp
                required:
                - requestId
                - data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        type:
                          type: string
                required:
                - requestId
                - errors
              examples:
                example:
                  summary: example
                  value:
                    requestId: 00000000-0000-0000-0000-000000000001
                    errors:
                    - type: server_error
                      code: internal_error
                      message: Internal Error
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        type:
                          type: string
                required:
                - requestId
                - errors
              examples:
                example:
                  summary: example
                  value:
                    requestId: 00000000-0000-0000-0000-000000000001
                    errors:
                    - type: endpoint_disabled
                      code: endpoint_disabled
                      message: This endpoint has been disabled temporarily
      security:
      - NONE: []
      parameters: []
      x-authentication:
      - NONE
      x-former-ws:
      - path: remotetime/get
        androidSupport: true
        appleSupport: false
        webSupport: true
        assignedCoreTeam: Platform
      x-rate-limit:
        mode: disabled
        count: 150
        intervalSec: 120
        property: remoteIP
      x-feature-group-team: Server Platform
      x-feature-group-name: Server Platform
    post:
      tags:
      - Time
      description: Retrieve the UNIX timestamp (in seconds) of the current time according to Dashlane servers
      operationId: time-GetRemoteTime
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  data:
                    type: object
                    properties:
                      timestamp:
                        description: The UNIX timestamp of the current time
                        type: integer
                    additionalProperties: false
                    required:
                    - timestamp
                required:
                - requestId
                - data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        type:
                          type: string
                required:
                - requestId
                - errors
              examples:
                example:
                  summary: example
                  value:
                    requestId: 00000000-0000-0000-0000-000000000001
                    errors:
                    - type: server_error
                      code: internal_error
                      message: Internal Error
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        type:
                          type: string
                required:
                - requestId
                - errors
              examples:
                example:
                  summary: example
                  value:
                    requestId: 00000000-0000-0000-0000-000000000001
                    errors:
                    - type: endpoint_disabled
                      code: endpoint_disabled
                      message: This endpoint has been disabled temporarily
      security:
      - NONE: []
      parameters: []
      x-authentication:
      - NONE
      x-former-ws:
      - path: remotetime/get
        androidSupport: true
        appleSupport: false
        webSupport: true
        assignedCoreTeam: Platform
      x-rate-limit:
        mode: disabled
        count: 150
        intervalSec: 120
        property: remoteIP
      x-feature-group-team: Server Platform
      x-feature-group-name: Server Platform
components:
  securitySchemes:
    NONE:
      type: http
      description: Does not require anything to access the endpoint
      scheme: x-dashlane-auth-none
    PublicAPIToken:
      type: http
      scheme: bearer
      description: Bearer authentication with DLP token
